#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# words2voice TTS — Cloudflare Tunnel Setup
#
# Run this ONCE after:
#   1. Docker TTS container is running (Step 1 done ✅)
#   2. You are logged into your Cloudflare account in a browser
#
# Usage:  bash setup-tunnel.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

TUNNEL_NAME="words2voice-tts"
TTS_HOSTNAME="tts.https://words2voice.vercel.app/"
TTS_LOCAL_URL="http://localhost:8000"
CLOUDFLARED_DIR="$HOME/.cloudflared"

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  words2voice — Cloudflare Tunnel Setup"
echo "═══════════════════════════════════════════════════════"
echo ""

# ── Step 1: Install cloudflared ───────────────────────────────────────────────
if ! command -v cloudflared &>/dev/null; then
  echo "▶  Installing cloudflared..."
  curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o /tmp/cloudflared.deb
  sudo dpkg -i /tmp/cloudflared.deb
  echo "✅  cloudflared installed: $(cloudflared --version)"
else
  echo "✅  cloudflared already installed: $(cloudflared --version)"
fi

# ── Step 2: Login (opens browser) ─────────────────────────────────────────────
echo ""
echo "▶  Logging into Cloudflare..."
echo "   A browser window will open. Authorise the tunnel for your"
echo "   'https://words2voice.vercel.app/' zone. The cert.pem will be saved to ~/.cloudflared/"
echo ""
cloudflared tunnel login

# ── Step 3: Create the named tunnel ───────────────────────────────────────────
echo ""
echo "▶  Creating tunnel '$TUNNEL_NAME'..."
# If tunnel already exists, skip creation
if cloudflared tunnel list 2>/dev/null | grep -q "$TUNNEL_NAME"; then
  echo "   Tunnel '$TUNNEL_NAME' already exists — reusing it."
else
  cloudflared tunnel create "$TUNNEL_NAME"
  echo "✅  Tunnel '$TUNNEL_NAME' created."
fi

# Get tunnel ID
TUNNEL_ID=$(cloudflared tunnel list --output json 2>/dev/null \
  | python3 -c "import sys,json; tuns=json.load(sys.stdin); \
    print(next(t['id'] for t in tuns if t['name']=='$TUNNEL_NAME'))")

echo "   Tunnel ID: $TUNNEL_ID"

# ── Step 4: Create DNS route ───────────────────────────────────────────────────
echo ""
echo "▶  Routing DNS: $TTS_HOSTNAME → tunnel $TUNNEL_ID..."
cloudflared tunnel route dns "$TUNNEL_NAME" "$TTS_HOSTNAME" || \
  echo "   (DNS route may already exist — that is fine)"

# ── Step 5: Write the config file ─────────────────────────────────────────────
CREDENTIALS_FILE="$CLOUDFLARED_DIR/${TUNNEL_ID}.json"

mkdir -p "$CLOUDFLARED_DIR"
cat > "$CLOUDFLARED_DIR/config.yml" << EOF
# words2voice TTS — Cloudflare Tunnel config
# Generated by setup-tunnel.sh
tunnel: ${TUNNEL_ID}
credentials-file: ${CREDENTIALS_FILE}

ingress:
  - hostname: ${TTS_HOSTNAME}
    service: ${TTS_LOCAL_URL}
    originRequest:
      connectTimeout: 30s
      # TTS synthesis can take 10-120s on CPU — raise read timeout accordingly
      proxyReadTimeout: 180s
  - service: http_status:404
EOF

echo "✅  Config written to $CLOUDFLARED_DIR/config.yml"

# ── Step 6: Test the tunnel (foreground, Ctrl+C to stop) ─────────────────────
echo ""
echo "═══════════════════════════════════════════════════════"
echo "  Setup complete! ✅"
echo ""
echo "  Your TTS service will be accessible at:"
echo "  https://${TTS_HOSTNAME}"
echo ""
echo "  Use this as TTS_ENGINE_URL in Render:"
echo "  https://${TTS_HOSTNAME}"
echo ""
echo "  Next steps:"
echo "  1. Test the tunnel:  cloudflared tunnel run $TUNNEL_NAME"
echo "  2. Install as service (auto-start on reboot):"
echo "     sudo cloudflared service install"
echo "     sudo systemctl enable cloudflared"
echo "     sudo systemctl start cloudflared"
echo "═══════════════════════════════════════════════════════"
